[TMP] Revert "selene: drop ignore neverallows"
sir why neverallow keep bullying me :(
idek where they comes from

FAILED: //system/sepolicy:precompiled_sepolicy Compiling cil files for precompiled_sepolicy [common]
Outputs: out/soong/.intermediates/system/sepolicy/precompiled_sepolicy/android_common/precompiled_sepolicy
Error: exited with code: 1
Output:
neverallow check failed at out/soong/.intermediates/system/sepolicy/plat_sepolicy.cil/android_common/plat_sepolicy.cil:26060 from system/sepolicy/private/property.te:64
  (neverallow domain base_typeattr_845 (file (ioctl read write create setattr lock relabelfrom append unlink link rename open watch watch_mount watch_sb watch_with_perm watch_reads)))
    <root>
    allow at out/soong/.intermediates/system/sepolicy/plat_sepolicy.cil/android_common/plat_sepolicy.cil:9321
      (allow dumpstate property_type (file (read getattr map open)))
    <root>
    allow at out/soong/.intermediates/system/sepolicy/plat_sepolicy.cil/android_common/plat_sepolicy.cil:12666
      (allow init property_type (file (read write create getattr setattr relabelto append map unlink rename open)))
    <root>
    allow at out/soong/.intermediates/system/sepolicy/plat_pub_versioned.cil/android_common/plat_pub_versioned.cil:6769
      (allow dumpstate_34_0 property_type (file (read getattr map open)))
    <root>
    allow at out/soong/.intermediates/system/sepolicy/plat_pub_versioned.cil/android_common/plat_pub_versioned.cil:8974
      (allow init_34_0 property_type (file (read write create getattr setattr relabelto append map unlink rename open)))
    Only first 4 of 20 matching rules shown (use "-v" to show all)

This reverts commit 536136610c26321088fb4d493888561f37b5cb86.

one day

Signed-off-by: fukiame <fukiame@proton.me>